### ISSUE TITLE
Design core data models

### ISSUE THREAD

**Issue by eugengi** [apexDev37/Agizo#1]
## Overview
To support core backend service, _"create new `customer` and `order` resources"_, implement the following required core models.

### Rationale
Given no explicit requirements, we don't need to implement a `Product` model at this initial iteration. We can _simply_ allow our client to define arbitrary `Order` item(s) and have our server process those requests.

This simplicity provides the following benefits:
- We have one less model to manage
- We have less inter-model communication
- Fewer tests to initially design and create
- Avoid having to seed our database with `Product` data
- We don't need to be concerned with validating `Product` data
- We don't need logic in place to handle product availability or inventory

> 💡 Our backend service assumes the capability to process all incoming orders from _authorized_ customers.

This captures our backend service's core functional intent while circumventing unnecessary complexity or overhead.

### Task list
- [ ] Create base auth `User` model
- [ ] Create a `Customer` profile
- [ ] Create a `Order` model

**Note:** Leave a door for an extension by design to add a `Product` model in later iterations with minimal _cost_ of change.
